### PR TITLE
Modification of pacman4console.

### PR DESCRIPTION
**Pull request by Maxython**
The reason for the change is [here](https://github.com/termux/termux-packages/discussions/7502).

### CODE REVIEW

**Comment by Grimler91** [comment]
Please bump the package as well

**Comment by Maxython** [comment]
I'm sorry, I didn't understand you ._.

**Comment by Grimler91** [comment]
Everytime a package is modified TERMUX_PKG_REVISION needs to be increased by 1 as well, otherwise apt and/or aptly will complain

**Comment by Maxython** [comment]
Ok

**Pull request merged**
