### PR TITLE
Update Nudoku to 2.1.0

### PR DESCRIPTION
**Pull request by omecamtiv**
Nudoku updated from 2.0.0 to 2.1.0
Built tested in termux.

### CODE REVIEW

**Comment by Grimler91** [comment]
Thanks for the PR. The newer versions of nudoku requires gettext >= 0.20, which is not available in the ubuntu version we use in the docker image. To build it we would have to download and install a newer gettext version in a hostbuild step

**Comment by omecamtiv** [comment]
I run into a problem while compiling. Installing gettext in termux resolved the issue. Actually i thought gettext is part of the build environment. Can you please tell me if I have to make any changes in build.sh?

**Comment by Grimler91** [comment]
> Actually i thought gettext is part of the build environment

If we by build environment mean the docker image where we cross-compile packages for termux, then yes, it is part of the build environment, but version 0.19:
```
$ sudo ./scripts/run-docker.sh gettext --version
Running container 'termux-package-builder' from image 'termux/package-builder'...
gettext (GNU gettext-runtime) 0.19.8.1
Copyright (C) 1995-1997, 2000-2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
```

> Can you please tell me if I have to make any changes in build.sh?

To make it work in the docker image we would have to download gettext's source code and build it from source in a termux_step_host_build() function. I have previously considered that too much of a hassle for just nudoku, once we update the ubuntu version in the docker image to a newer version we get gettext > 0.20 and can update nudoku. There's no plan for doing that right now though, maybe after we have managed to update the ndk used

**Comment by omecamtiv** [comment]
Yeah now it's clear to me. Thanks for these informations. Learnt a lot from these infos.

**Comment by Grimler91** [comment]
@omecamtiv yes, that works fine!

**Comment by Grimler91** [comment]
Closing for now since this repo is being archived (and all packages moved to termux-packages)

**Pull request closed without merging**
