### PR TITLE
Added frogcomposband package build

### PR DESCRIPTION
**Pull request by Archenoth**
I've managed to get several roguelikes to build and run on Termux, and after writing a [big 'ol post](https://archenoth.com/tech/2020/05/29/Roguelikes-in-Termux.html) about doing that, and after helping quite a few people to get them up and running, I figured that I might as well contribute to the repos itself!

This is the first of several packages I plan on making, though I wanted to make sure everything is on the up and up contribution-wise before I build the scripts for the other ones. ^^

The game itself is FrogComposband, which is one of the most popular bands out there currently, which features an overworld, a *lot* of quests, and is one of the most played on [angband.live](https://angband.live) currently.

A screenshot of the FrogComposband overworld

### CODE REVIEW

**Comment by Archenoth** [comment]
The force push was amending the license field. Angband is dual-licensed with the GPL and Angband licenses, but variants of it that were forked from earlier versions are just [the Angband license](https://www.openhub.net/licenses/The_Angband_License) which is a single line which states:

```
This software may be copied and distributed for educational, research, and not for profit purposes provided that this copyright and statement are included in all such copies. Other copyrights may also apply.
```

(And that seemed to break the tests somehow??)

**Comment by Grimler91** [comment]
Hi,  nice!

> Does this mean that this roguelike is incompatible with being packaged?

It means that we cannot host it on bintray in open-source accounts (i.e. bintray.com/grimler and bintray.com/xeffyr), it would be fine to have it in the main termux-packages repository (bintray.com/termux) though, "custom" licenses are acceptable there since they sponsor us, so you can open a PR towards the main repository and specify `TERMUX_PKG_LICENSE="custom"`, and install the angband license to `$PREFIX/share/doc/<package-name>`

**Comment by Archenoth** [comment]
Oh! Thanks for the heads up! I might just do that~ ^^

The Angband license was made before GPL existed, and while it was trying to be as open as possible (To allow free redistribution and modification), it still required a couple tweaks before it was entirely compatible with free software licenses that came later.

But yeah, I can definitely extract that license into that path.

**Comment by Archenoth** [comment]
Alright! So the package now has a custom license set, and installs a `LICENSE` file containing the original Angband one~
It's nice seeing that test being green again.

How does this look? ^^

**Comment by Archenoth** [comment]
> so you can open a PR towards the main repository and specify TERMUX_PKG_LICENSE="custom", and install the angband license to $PREFIX/share/doc/<package-name>

Oh wait... By "main repository", do you mean the non-game [termux-packages?](https://github.com/termux/termux-packages)

If so, I read that *very* differently until a few seconds ago.

**Comment by Grimler91** [comment]
> > so you can open a PR towards the main repository and specify TERMUX_PKG_LICENSE="custom", and install the angband license to $PREFIX/share/doc/
> 
> Oh wait... By "main repository", do you mean the non-game [termux-packages?](https://github.com/termux/termux-packages)
> 
> If so, I read that _very_ differently until a few seconds ago.

Yeah, only packages with one of these licenses can be uploaded to bintray.com/grimler/game-packages-24:
```
AFL-2.1, AFL-3.0, AGPL-V3, Apache-1.0, Apache-1.1, Apache-2.0, APL-1.0, APSL-2.0, Artistic-License-2.0, Attribution, Bouncy-Castle, BSD, BSD 2-Clause, BSD 3-Clause, BSL-1.0, CA-TOSL-1.1, CC0-1.0, CDDL-1.0, Codehaus, CPAL-1.0, CPL-1.0, CPOL-1.02, CUAOFFICE-1.0, Day, Day-Addendum, ECL2, Eiffel-2.0, Entessa-1.0, EPL-1.0, EPL-2.0, EUDATAGRID, EUPL-1.1, Fair, Facebook-Platform, Frameworx-1.0, Go, GPL-2.0, GPL-2.0+CE, GPL-3.0, Historical, HSQLDB, IBMPL-1.0, ImageMagick, IPAFont-1.0, ISC, IU-Extreme-1.1.1, JA-SIG, JSON, JTidy, LGPL-2.1, LGPL-3.0, Libpng, LPPL-1.0, Lucent-1.02, MirOS, MIT, Motosoto-0.9.1, Mozilla-1.1, MPL-2.0, MS-PL, MS-RL, Multics, NASA-1.3, NAUMEN, Nethack, Nokia-1.0a, NOSL-3.0, NTP, NUnit-2.6.3, NUnit-Test-Adapter-2.6.3, OCLC-2.0, Openfont-1.1, Opengroup, OpenSSL, OSL-3.0, PHP-3.0, PostgreSQL, Public Domain, Public Domain - SUN, PythonPL, PythonSoftFoundation, QTPL-1.0, Real-1.0, RicohPL, RPL-1.5, Scala, SimPL-2.0, Sleepycat, SUNPublic-1.0, Sybase-1.0, TMate, Unlicense, UoI-NCSA, VIM License, VovidaPL-1.0, W3C, WTFPL, wxWindows, Xnet, ZLIB, ZPL-2.0
```

We don't have the same restriction in github.com/termux/termux-packages though, so could you open a PR against the main repo instead?

**Comment by Archenoth** [comment]
Alright! [Done!](https://github.com/termux/termux-packages/pull/5740) (Which means this PR probably isn't really needed anymore.)

Thank you for your patience with me though!

**Pull request closed without merging**
